version: "3.8"

services:
  client:
    build:
      context: ./client
    ports:
      - "5000:5000"
    container_name: client
    depends_on:
      - backend
      - nginx

  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    restart: always
    container_name: backend
    depends_on:
      - nginx

  nginx:
    restart: always
    image: nginx:latest
    container_name: nginx
    volumes:
      - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - "80:80"
